const GET_ARTICLES = 'GET_ARTICLES';
const GET_ARTICLE = 'GET_ARTICLE';
const DELETE_ARTICLE = 'DELETE_ARTICLE';
const CREATE_ARTICLE = 'CREATE_ARTICLE';
const UPDATE_ARTICLE = 'UPDATE_ARTICLE';

export { GET_ARTICLES, GET_ARTICLE, CREATE_ARTICLE, DELETE_ARTICLE, UPDATE_ARTICLE }

